/****************************************************************************
 * @file    : lin_define.h
 * @author  : Novosns MCU Team
 * @version : V2.0
 * @Date    : 2023/4/7
 * @brief   : lin stack file 
 * @note
 * Copyright (C) 2023 Novosense All rights reserved.
 ****************************************************************************/
#ifndef __LIN_DEFINE_H
#define __LIN_DEFINE_H

//======================================================================
// Compiler switches for test and debug purposes
//======================================================================


#if 0    // ##### defined in project options for target 'Debug'
  #define DEBUG                   // if defined, some debug options can be enabled during implementation/evaluation
                                  // must be disabled for final software release
#endif

#ifdef DEBUG
  //#define  DEBUG_PORT_TOGGLE       // if defined, some ports are configured to output test signals
  #define DEBUG_ERROR_COUNTER      // if defined, three error counters are sent in l_frame[RESPONSE_ERROR_FRAME] byte 4..6
  #define DEBUG_TRACE_ENABLE
#endif

//======================================================================
// Compiler switches for different options
//======================================================================

#define USE_LGPIO_0_1_2
#if (defined USE_LGPIO_0_1_2) && (defined DEBUG_PORT_TOGGLE)
  #error "### USE_LGPIO_0_1_2 and DEBUG_PORT_TOGGLE cannot be defined simultaneously !!!"
#endif

#define  L_NAD_NVR    // if defined, NAD is read from NVR (if there is a valid NAD stored)

#define  L_PID_NVR    // if defined, PID table is read from NVR (if there is a valid PID table stored)

#define L_UDS_BOOTLOADER_UPDATE // if user want to use uds bootloader update firmware , please define micro
//======================================================================
// global definitions
//======================================================================
#define SW_VERSION    0x20

#define TRUE            1
#define FALSE          !TRUE

#ifndef NULL
  #define NULL         ((void *)0)    // the NULL pointer
#endif

// UART and LIN setup
// ------------------
#define LIN_LOM          0            // 0: LIN port switched off by HW for VBVDD < VBVDDU
                                      // 1: LIN port not switched off by HW for VBVDD < VBVDDU
  
#define SLEW_10_KBPS        3                        // slew rate for 10kbps=1V/us
#define SLEW_20_KBPS        2                        // slew rate for 20kbps=2V/us
//#define SLEW_INFINITE    1                        // slew rate=infinite
#define SLEW_INFINITE        0                        // slew rate=infinite

// definition of LINUART interrupt flags
#define  LINUART_TXC      BIT_0
#define  LINUART_RXC      BIT_1
#define  LINUART_RXB      BIT_2
#define  LINUART_TXB      BIT_3
#define  LINUART_RXOV     BIT_4
#define  LINUART_PE       BIT_5
#define  LINUART_BRSY     BIT_6
#define  LINUART_TXEND    BIT_7
#define  LINUART_FE       BIT_8
#define  LINUART_TO       BIT_9
#define  LINUART_TXFO     BIT_10
#define  LINUART_RXFO     BIT_11
#define  LINUART_TXFF     BIT_12
#define  LINUART_RXFF     BIT_13
#define  LINUART_TXFE     BIT_14
#define  LINUART_RXFE     BIT_15
#define  LINUART_TXFL     BIT_16
#define  LINUART_RXFL     BIT_17
#define  LINUART_TXFC     BIT_18
#define  LINUART_TXERR    BIT_19
#define  LINUART_BRK      BIT_20
#define  LINUART_BRRERRIF BIT_31

// definition of LIN interrupt flags
#define  LIN_LINFE    BIT_0
#define  LIN_LINRE    BIT_1
#define  LIN_OC       BIT_2
#define  LIN_DOMTO    BIT_3
#define  LIN_BEND     BIT_4


/* following code generated by LIN Tool From LDF */

#define LIN_BITRATE      19200    // supported values: 1000, 2400， 4800， 9600， 10400, 19200

// UART clock = 48MHz
// Note: UART_BITLEN is used for definition of the length for the baud Rate
#if LIN_BITRATE == 1000
    #define UART_BRR            (48000)
    #define LIN_SLEW            SLEW_10_KBPS
#elif LIN_BITRATE == 2400
    #define UART_BRR            (20000 - 1)
    #define LIN_SLEW            SLEW_10_KBPS
#elif LIN_BITRATE == 4800
    #define UART_BRR            (10000 - 1)
    #define LIN_SLEW            SLEW_10_KBPS
#elif LIN_BITRATE == 9600
    #define UART_BRR            (5000 - 1)
    #define LIN_SLEW            SLEW_10_KBPS
#elif LIN_BITRATE == 10400
    #define UART_BRR            (4615 - 1)
    #define LIN_SLEW            SLEW_10_KBPS
#elif LIN_BITRATE == 19200
    #define UART_BRR            (2500 - 1)
    #define LIN_SLEW            SLEW_20_KBPS
#elif LIN_BITRATE == 20000
    #define UART_BRR            (2400)
    #define LIN_SLEW            SLEW_20_KBPS
#endif


#define  L_LIN_2_2                // if defined, LIN V2.2 is supported (otherwise, LIN V2.0 is supported)
                                  // The following LIN 2.2 features are implemented:
                                  //  - configuration frame "AssignFrameIdRange"
                                  //  - obsolete function "Assign Frame Identifier" deleted
                                  //  - message IDs deleted
                                  //  - support for message IDs within "Read by Identifiers" deleted
                                  
#define   L_EVENT_TRIGGERED_FRAME // if set, an event triggered frame is enabled

#define   L_SNPD_BSM              // if defined, LIN SNPD (via Bus Shunt Method 1) is enabled

#define   L_APPLICATION_EXAMPLE   // if defined, a simple application is enabled:
                                  // - control some ports via LIN frame ID = 13
                                  // - provide some status information in LIN frame ID=11

#endif          /* __LIN_DEFINE_H */
